### ISSUE TITLE
Support for YP 3.1 ''dunfell' planned ?

### ISSUE THREAD

**Issue by dl9pf** [foss-for-synopsys-dwc-arc-processors/meta-synopsys#5]
Are there plans for supporting dunfell ?

**Comment by abrodkin** [comment]
Just to add some context for people not vary familiar with Yocto, we're talking about Yocto v3.1 code name "Dunfell" (https://wiki.yoctoproject.org/wiki/Releases).
@dl9pf sure since our goal is to keep support of upstream projects and especially since "Dunfell" is marked as the first ever LTS branch of Yocto we'll add necessary bits in our layer.

@EvgeniiDidin could you please take a look at what's missing for it or we may declare it already supported?

**Comment by EvgeniiDidin** [comment]
Hi @dl9pf ,

I prepared two branches, first is compatible with poky_3.1 release:
https://github.com/foss-for-synopsys-dwc-arc-processors/meta-synopsys/tree/yocto_3.1_compatible
Second is based on yocto_3.1_compatible with AGL related changes:
https://github.com/foss-for-synopsys-dwc-arc-processors/meta-synopsys/tree/dunfell-agl

I tried to build  AGL from **next**  branch with second branch(dunfell-agl) and observed only fails related to AGL applications.
Should I send a pull request to AGL-repo to update default.xml in **next** branch?

**Comment by dl9pf** [comment]
Please add the bsp to the master AGL-repo default.xml  and from there we get the templates back. 
We should complete this this week before the BSPs freeze.

**Comment by EvgeniiDidin** [comment]
Support for YP 3.1 "dunfell" was introduced in this meta-synopsys branch:
https://github.com/foss-for-synopsys-dwc-arc-processors/meta-synopsys/tree/yocto_3.1_compatible
For AGL there is a branch based on yocto_3.1_compatible:
https://github.com/foss-for-synopsys-dwc-arc-processors/meta-synopsys/tree/dunfell-agl
